name: localization
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: any
  provider: ^6.1.5+1
  image_picker: ^1.2.0
  cloud_firestore: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
