// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNdZ0fvP7y2HPVPVT0wc44QFYUwwYBrFQ',
    appId: '1:611075489875:android:cb1748ef7d58fc597d86a6',
    messagingSenderId: '611075489875',
    projectId: 'eventsapp-ca1c0',
    storageBucket: 'eventsapp-ca1c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACtt903aqkKUyGuZ7Rv-o_PiQjTZfW2S0',
    appId: '1:611075489875:ios:f52510d8b030bed87d86a6',
    messagingSenderId: '611075489875',
    projectId: 'eventsapp-ca1c0',
    storageBucket: 'eventsapp-ca1c0.firebasestorage.app',
    iosBundleId: 'com.example.localization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACtt903aqkKUyGuZ7Rv-o_PiQjTZfW2S0',
    appId: '1:611075489875:ios:f52510d8b030bed87d86a6',
    messagingSenderId: '611075489875',
    projectId: 'eventsapp-ca1c0',
    storageBucket: 'eventsapp-ca1c0.firebasestorage.app',
    iosBundleId: 'com.example.localization',
  );
}
